# Generated by Django 4.2 on 2024-12-06 10:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('Bedsitter', 'Bedsitter'), ('One Bedroom', 'One Bedroom'), ('Two Bedroom', 'Two Bedroom'), ('Apartment', 'Apartment'), ('Shop', 'Shop')], max_length=30)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Occupied', 'Occupied'), ('For Sale', 'For Sale')], max_length=30)),
                ('location', models.CharField(choices=[('Ole Kasasi A', 'Ole Kasasi A'), ('Ole Kasasi B', 'Ole Kasasi B'), ('Tumaini', 'Tumaini'), ('Sironik Road', 'Sironik Road'), ('Mayor Road', 'Mayor Road'), ('Masai Lodge Road', 'Masai Lodge Road'), ('Naivas', 'Naivas'), ('Tuskys', 'Tuskys'), ('Kware', 'Kware'), ('Gataka Road', 'Gataka Road')], max_length=40)),
                ('dateadded', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Landlord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=16)),
                ('repeat_pass', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='HouseImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='NewHouses/')),
                ('description', models.TextField()),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app1.house')),
            ],
        ),
        migrations.AddField(
            model_name='house',
            name='landlord',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='houses', to='app1.landlord'),
        ),
    ]
