# Generated by Django 4.2 on 2024-12-06 11:54

import app1.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(help_text='Enter price as an integer value (e.g., 7000)', unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='house',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to=app1.utils.house_main_image_upload_to),
        ),
        migrations.AlterField(
            model_name='houseimage',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='houseimage',
            name='image',
            field=models.ImageField(upload_to=app1.utils.house_image_upload_to),
        ),
        migrations.AddField(
            model_name='house',
            name='price_ranges',
            field=models.ManyToManyField(blank=True, related_name='houses', to='app1.pricerange'),
        ),
    ]
