# Generated by Django 4.2 on 2024-12-06 12:15

import app1.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_pricerange_house_main_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='house',
            options={'ordering': ['-dateadded']},
        ),
        migrations.AlterField(
            model_name='house',
            name='landlord',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_houses', to='app1.landlord'),
        ),
        migrations.AlterField(
            model_name='house',
            name='main_image',
            field=models.ImageField(blank=True, help_text='Upload the main image for the house', null=True, upload_to=app1.utils.house_main_image_upload_to),
        ),
        migrations.AlterField(
            model_name='house',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Occupied', 'Occupied'), ('For Sale', 'For Sale')], default='Occupied', max_length=30),
        ),
    ]
