# Generated by Django 4.2 on 2025-01-04 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_house_options_alter_house_landlord_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='price_ranges',
        ),
        migrations.AddField(
            model_name='house',
            name='agent_name',
            field=models.CharField(default='Jabez', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='house',
            name='agent_phone',
            field=models.CharField(default='0791751475', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='house',
            name='coordinates',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='pros',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='rent',
            field=models.TextField(choices=[('6500', '6500'), ('7000', '7000'), ('7500', '7500'), ('8000', '8000'), ('8500', '8500'), ('9000', '9000'), ('9500', '9500'), ('10000', '10000'), ('10500', '10500'), ('11000', '11000'), ('11500', '11500'), ('12000', '12000'), ('12500', '12500'), ('13000', '13000'), ('13500', '13500'), ('14000', '14000'), ('14500', '14500'), ('15000', '15000'), ('15500', '15500'), ('16000', '16000'), ('16500', '16500'), ('17000', '17000'), ('17500', '17500'), ('18000', '18000'), ('18500', '18500'), ('19000', '19000'), ('19500', '19500'), ('20000', '20000'), ('20500', '20500'), ('21000', '21000'), ('21500', '21500'), ('22000', '22000'), ('22500', '22500'), ('23000', '23000'), ('23500', '23500'), ('24000', '24000'), ('24500', '24500'), ('25000', '25000'), ('25500', '25500'), ('26000', '26000'), ('26500', '26500'), ('27000', '27000'), ('27500', '27500'), ('28000', '28000'), ('28500', '28500'), ('29000', '29000'), ('29500', '29500'), ('30000', '30000')], default=6000, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='house',
            name='landlord',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='houses', to='app1.landlord'),
        ),
        migrations.AlterField(
            model_name='house',
            name='type',
            field=models.TextField(choices=[('Bedsitter', 'Bedsitter'), ('One Bedroom', 'One Bedroom'), ('Two Bedroom', 'Two Bedroom'), ('Apartment', 'Apartment'), ('Shop', 'Shop')], max_length=30),
        ),
        migrations.DeleteModel(
            name='PriceRange',
        ),
    ]
