# Generated by Django 4.2 on 2025-01-08 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_alter_house_rent_alter_house_type'),
    ]

    operations = [
    ]
