# Generated by Django 4.2 on 2025-01-08 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_auto_20250108_2229'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='house',
            name='location',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='house',
            name='main_image',
            field=models.ImageField(blank=True, help_text='Upload the main image for the house', null=True, upload_to='houses/'),
        ),
        migrations.RemoveField(
            model_name='house',
            name='rent',
        ),
        migrations.RemoveField(
            model_name='house',
            name='type',
        ),
        migrations.AddField(
            model_name='house',
            name='rent',
            field=models.ManyToManyField(blank=True, related_name='houses', to='app1.rent'),
        ),
        migrations.AddField(
            model_name='house',
            name='type',
            field=models.ManyToManyField(blank=True, related_name='houses', to='app1.type'),
        ),
    ]
