# Generated by Django 4.2 on 2025-01-08 19:58

import app1.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_rent_type_alter_house_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='location',
            field=models.CharField(choices=[('Ole Kasasi A', 'Ole Kasasi A'), ('Ole Kasasi B', 'Ole Kasasi B'), ('Tumaini', 'Tumaini'), ('Sironik Road', 'Sironik Road'), ('Mayor Road', 'Mayor Road'), ('Masai Lodge Road', 'Masai Lodge Road'), ('Naivas', 'Naivas'), ('Tuskys', 'Tuskys'), ('Kware', 'Kware'), ('Gataka Road', 'Gataka Road')], max_length=40),
        ),
        migrations.AlterField(
            model_name='house',
            name='main_image',
            field=models.ImageField(blank=True, help_text='Upload the main image for the house', null=True, upload_to=app1.utils.house_main_image_upload_to),
        ),
        migrations.RemoveField(
            model_name='house',
            name='rent',
        ),
        migrations.RemoveField(
            model_name='house',
            name='type',
        ),
        migrations.DeleteModel(
            name='Rent',
        ),
        migrations.DeleteModel(
            name='Type',
        ),
        migrations.AddField(
            model_name='house',
            name='rent',
            field=models.CharField(choices=[('6500', '6500'), ('7000', '7000'), ('7500', '7500'), ('8000', '8000'), ('8500', '8500'), ('9000', '9000'), ('9500', '9500'), ('10000', '10000'), ('10500', '10500'), ('11000', '11000'), ('11500', '11500'), ('12000', '12000'), ('12500', '12500'), ('13000', '13000'), ('13500', '13500'), ('14000', '14000'), ('14500', '14500'), ('15000', '15000'), ('15500', '15500'), ('16000', '16000'), ('16500', '16500'), ('17000', '17000'), ('17500', '17500'), ('18000', '18000'), ('18500', '18500'), ('19000', '19000'), ('19500', '19500'), ('20000', '20000'), ('20500', '20500'), ('21000', '21000'), ('21500', '21500'), ('22000', '22000'), ('22500', '22500'), ('23000', '23000'), ('23500', '23500'), ('24000', '24000'), ('24500', '24500'), ('25000', '25000'), ('25500', '25500'), ('26000', '26000'), ('26500', '26500'), ('27000', '27000'), ('27500', '27500'), ('28000', '28000'), ('28500', '28500'), ('29000', '29000'), ('29500', '29500'), ('30000', '30000')], default=6000, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='house',
            name='type',
            field=models.CharField(choices=[('Bedsitter', 'Bedsitter'), ('One Bedroom', 'One Bedroom'), ('Two Bedroom', 'Two Bedroom'), ('Apartment', 'Apartment'), ('Shop', 'Shop')], default='Bedsitter', max_length=30),
            preserve_default=False,
        ),
    ]
