# Generated by Django 4.2 on 2025-01-09 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_alter_house_location_alter_house_main_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='rent',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='house',
            name='type',
            field=models.JSONField(),
        ),
    ]
