# Generated by Django 4.2 on 2025-05-25 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_remove_landlord_username_alter_landlord_email'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='landlord',
            managers=[
            ],
        ),
    ]
