# Generated by Django 4.2 on 2024-11-29 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_house_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='images',
            field=models.ImageField(upload_to='NewHouses/'),
        ),
    ]
