# Generated by Django 4.2 on 2024-12-01 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_house_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='images',
        ),
        migrations.CreateModel(
            name='HouseImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='NewHouses/')),
                ('description', models.TextField()),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app1.house')),
            ],
        ),
    ]
