name: Deploy Backend to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Upload Backend folder to EC2
        run: |
          rsync -avz --delete ./Backend/ ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:${{ secrets.DEPLOY_DIR }}/Backend/

      - name: Deploy on EC2 (venv, env, install, gunicorn)
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << EOF
            cd ${{ secrets.DEPLOY_DIR }}

            # Set up virtualenv if not already
            if [ ! -d "venv" ]; then
              python3 -m venv venv
            fi
            source venv/bin/activate

            # Install dependencies
            pip install --upgrade pip
            pip install -r Backend/requirements.txt

            # Write .env file to Backend/Jay/Jay/.env
            ENV_PATH="Backend/Jay/Jay/.env"
            mkdir -p "\$(dirname "\$ENV_PATH")"

            echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" > "\$ENV_PATH"
            echo "DJANGOAPPMODE=Prod" >> "\$ENV_PATH"
            echo "USEDEBUGDB=False" >> "\$ENV_PATH"
            echo "EMAIL_HOST_USER=${{ secrets.EMAIL_HOST_USER }}" >> "\$ENV_PATH"
            echo "EMAIL_HOST_PASSWORD=${{ secrets.EMAIL_HOST_PASSWORD }}" >> "\$ENV_PATH"
            echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> "\$ENV_PATH"
            echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> "\$ENV_PATH"
            echo "AWS_STORAGE_BUCKET_NAME=${{ secrets.AWS_STORAGE_BUCKET_NAME }}" >> "\$ENV_PATH"
            echo "AWS_S3_REGION_NAME=${{ secrets.AWS_S3_REGION_NAME }}" >> "\$ENV_PATH"
            echo "DB_NAME=${{ secrets.DB_NAME }}" >> "\$ENV_PATH"
            echo "DB_USER=${{ secrets.DB_USER }}" >> "\$ENV_PATH"
            echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> "\$ENV_PATH"
            echo "DB_HOST=${{ secrets.DB_HOST }}" >> "\$ENV_PATH"
            echo "DB_PORT=5432" >> "\$ENV_PATH"
            echo "FRONTEND_URL=${{ secrets.FRONTEND_URL }}" >> "\$ENV_PATH"

            # Restart Gunicorn
            sudo systemctl restart gunicorn
          EOF
